### ISSUE TITLE
masksize computation

### ISSUE THREAD

**Issue by banandan** [MicronSSD/unvme#11]
ses->masksize = (qsize + 63 / 64) * sizeof(u64);

Why is there a 63/64? 

Should it be ((qsize + 63) / 64)?

**Comment by sbradshawmicron** [comment]
Good catch.  The point of the adjustment is to overestimate the size of the mask to offset the potential underestimation of the integer divide.  It should be ((qsize + 63) / 64) else it's undersized and would lead to corruption.

FYI, Deyoung is out for a bit.  I'll let him address this in master when he returns.  Please be patient.

**Comment by ttDSSD-EMC** [comment]
It certainly is a typo, but just FYI, it doesn't lead to a bug because it's now massively oversized.  Assuming qsize was already a multiple of 64, then `masksize would become `qsize / 8` where now it becomes `(qsize + 1) * 8`.

**Comment by dhongMicron** [comment]
Thanks for catching the bug.  I've checked in the fix.
