### ISSUE TITLE
rdtsc_second() in unvme_complete_io

### ISSUE THREAD

**Issue by banandan** [MicronSSD/unvme#12]
I see max latencies greater than 10ms for a few 2MB sequential reads. It is due to rdtsc_second() within unvme_complete_io. If this was not done intentionally, it is probably better to call this once in the initialization step. 

The average latency is 1.2ms

**Comment by dhongMicron** [comment]
rdtsc_second() is an inline function that initializes tsc_ps once and returns that value afterward.  The only cost is an if statement so I woulnd't think it makes any difference.

**Comment by bala-a** [comment]
Yeah I didn't read it carefully. Only the first 2M read is 10ms

**Comment by banandan** [comment]
Yeah I didn't read it carefully. Only the first 2M read is 10ms
