### ISSUE TITLE
Problem using unvme for an Micron 9100 NVMe SSD 

### ISSUE THREAD

**Issue by arashta** [MicronSSD/unvme#18]
I have been using unvme for performance testing on a Micron 9100 NVMe SSD  device.
However, the reported read latency results seem unrealistic. For example, for qdepth = 1 and request size = 8 (4kB), the reported average read latency value is 22.7. I have done a lot of experiments with different request sizes, queue depths, and address access patterns. The achieved results are all strange and about 1/10 to 1/5 of the nominal value (130us) reported in the datasheet.
I have preconditioned the device by writing two times to the half of the available logical space. The experiments are done later in the written address space.
I also have done write/read tests in which, in the first round, the address space is written with specific data and then, in the second round, the previously written values are read. These experiments prove the correctness of both write and read operations.

**Comment by dhongMicron** [comment]
What software are you using for performance testing and latency measurements?

**Comment by arashta** [comment]
I run my experiments using the following two software:
1) The fio tool (using the fio engine provide by unvme),
2) My own C code that uses unvme_aread() and unvme_awrite() functions. It is pretty much similar to the unvme_lat_test.c.

**Comment by dhongMicron** [comment]
It wasn't clear that you're using fio which has blocksize parameter and not request size.  The performance numbers shown by fio should be right.  Are you saying the fio results are unrealistically better than the datasheet?  Have you tested with other drives (other than Micron)?  What is your machine configurations (CPU cores, speed, memory size, etc.)?  Please post your fio job files so I can try.

**Comment by arashta** [comment]
I have tested one other device and the results are all similar. I measured the time for plextor m8pe device for the following request sizes (the sizes are in blocks):
size	latency_average	latency_min	latency_max
8	12.60	5.37	662.38
16	14.30	6.44	650.16
32	20.59	6.90	661.15
64	27.06	17.26	648.18
128	42.27	18.84	659.90

For the micron device,  the following values are achieved:
size	latency_average	latency_min	latency_max
8	12.45	9.71	1806.92
16	14.16	10.89	1954.79
32	32.66	13.48	2086.83
64	42.51	14.06	2456.49
128	92.40	61.00	2081.50

For each request size, I run the experiments 10 times (2 minutes each, 20 minutes total), on an Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz server with 32GB of RAM and Ubuntu 16.04.2

As I see in the unvme_lat_test.c file, it reports the duration of time between request submission to the time that the (unvme_apoll(p->iod, 0) == 0) confirms request completion.  As the unvme tool has been tested on CentOS, then I was thinking that there may be a problem in the timing calculations (Ubuntu does not have a built-in version of usleep script). Therefore, I changed the timing measurements to use clock_gettime, e.g.:

clock_gettime(CLOCK_THREAD_CPUTIME_ID, &p->start_time);

However, the results do not change at all.


For the fio, I have been using the default job descriptions provided with the unvme package.

**Comment by arashta** [comment]
Making the results more readable:
**size    average min       max**
8        12.60      5.37      662.38
16      14.30      6.44      650.16
32      20.59      6.90      661.15
64      27.06      17.26    648.18
128    42.27      18.84      659.90

**Comment by arashta** [comment]
Sorry, the results seem to be hard to read. So, I repeat them here:
size	|| latency_average	|| latency_min	|| latency_max
8	|| 12.60	|| 5.37	|| 662.38
16	|| 14.30	|| 6.44	|| 650.16
32	|| 20.59	|| 6.90	|| 661.15
64	|| 27.06	|| 17.26	|| 648.18
128	|| 42.27	|| 18.84	|| 659.90

**Comment by dhongMicron** [comment]
I'm still confused by your data.  Fio doesn't know about block size and does not do size by number of blocks, only by number of bytes.

Did you run test/unvme-benchmark?  What is the output of an fio run?  
For example, results of numjobs=1 and iodepth=1 for random write on Micron SSD shows:

...
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=unvme_fio, iodepth=1
fio-2.19
Starting 1 thread
unvme_open 03:00.0/1 q=128x256 ncpus=32

test: (groupid=0, jobs=1): err= 0: pid=7710: Mon Sep 25 12:27:41 2017
  write: IOPS=45.7k, BW=178MiB/s (187MB/s)(20.1GiB/120001msec)
    slat (usec): min=0, max=16, avg= 0.14, stdev= 0.35
    clat (usec): min=17, max=3465, avg=21.34, stdev= 8.19
     lat (usec): min=20, max=3465, avg=21.48, stdev= 8.19
    clat percentiles (usec):
     |  1.00th=[   20],  5.00th=[   21], 10.00th=[   21], 20.00th=[   21],
     | 30.00th=[   21], 40.00th=[   21], 50.00th=[   21], 60.00th=[   21],
     | 70.00th=[   22], 80.00th=[   22], 90.00th=[   22], 95.00th=[   22],
     | 99.00th=[   23], 99.50th=[   23], 99.90th=[   26], 99.95th=[   27],
     | 99.99th=[   29]
    lat (usec) : 20=0.01%, 50=100.00%, 100=0.01%, 750=0.01%, 1000=0.01%
    lat (msec) : 2=0.01%, 4=0.01%
  cpu          : usr=23.39%, sys=76.66%, ctx=149, majf=0, minf=1537
  IO depths    : 1=150.1%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,5474759,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=178MiB/s (187MB/s), 178MiB/s-178MiB/s (187MB/s-187MB/s), io=20.1GiB (22.5GB), run=120001-120001msec

Disk stats (read/write):
  sda: ios=0/53, merge=0/48, ticks=0/10, in_queue=10, util=0.01%

**Comment by dhongMicron** [comment]
You can also run unvme-benchmark against inbox NVMe kernel driver (i.e. after test/unvme-setup reset).
Have you compared the UNVMe results with inbox driver using your approach?

Btw, with the latest UNVMe code, if you enable CPPFLAGS+=-DUNVME_IDENTITY_MAP_DMA, the UNVMe benchmark results should be a little better especially with higher number of jobs and queue depths.

**Comment by arashta** [comment]
Here are the fio input and outputs:

test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=unvme_fio, iodepth=1
fio-3.0-46-ga2b11
Starting 1 thread
unvme_open 04:00.0/1 q=128x256 ncpus=8

test: (groupid=0, jobs=1): err= 0: pid=2594: Tue Sep 26 00:48:01 2017
   read: IOPS=9567, BW=37.4MiB/s (39.2MB/s)(4485MiB/120001msec)
    slat (nsec): min=58, max=22990, avg=64.89, stdev=117.19
    clat (usec): min=84, max=656, avg=104.17, stdev= 7.09
     lat (usec): min=84, max=656, avg=104.24, stdev= 7.09
    clat percentiles (usec):
     |  1.00th=[   89],  5.00th=[   97], 10.00th=[   98], 20.00th=[   98],
     | 30.00th=[   99], 40.00th=[  100], 50.00th=[  101], 60.00th=[  111],
     | 70.00th=[  112], 80.00th=[  113], 90.00th=[  114], 95.00th=[  114],
     | 99.00th=[  116], 99.50th=[  116], 99.90th=[  124], 99.95th=[  126],
     | 99.99th=[  131]
   bw (  KiB/s): min=38188, max=38825, per=100.00%, avg=38494.07, stdev=153.89, samples=240
   iops        : min= 9547, max= 9706, avg=9623.27, stdev=38.35, samples=240
  lat (usec)   : 100=44.62%, 250=55.38%, 750=0.01%
  cpu          : usr=24.47%, sys=75.54%, ctx=152, majf=0, minf=0
  IO depths    : 1=149.8%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=1148099,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=37.4MiB/s (39.2MB/s), 37.4MiB/s-37.4MiB/s (39.2MB/s-39.2MB/s), io=4485MiB (4703MB), run=120001-120001msec

Disk stats (read/write):
  sda: ios=0/44, merge=0/29, ticks=0/84, in_queue=84, util=0.05%

**Comment by arashta** [comment]
test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=unvme_fio, iodepth=4
fio-3.0-46-ga2b11
Starting 1 thread
unvme_open 04:00.0/1 q=128x256 ncpus=8

test: (groupid=0, jobs=1): err= 0: pid=2635: Tue Sep 26 00:51:03 2017
   read: IOPS=34.7k, BW=136MiB/s (142MB/s)(15.9GiB/120001msec)
    slat (nsec): min=58, max=23154, avg=67.74, stdev=122.91
    clat (nsec): min=351, max=730974, avg=114821.41, stdev=28571.60
     lat (usec): min=9, max=731, avg=114.89, stdev=28.57
    clat percentiles (usec):
     |  1.00th=[   89],  5.00th=[   97], 10.00th=[   98], 20.00th=[   99],
     | 30.00th=[  100], 40.00th=[  101], 50.00th=[  111], 60.00th=[  112],
     | 70.00th=[  113], 80.00th=[  115], 90.00th=[  161], 95.00th=[  184],
     | 99.00th=[  212], 99.50th=[  245], 99.90th=[  289], 99.95th=[  293],
     | 99.99th=[  318]
   bw (  KiB/s): min=137678, max=143174, per=100.00%, avg=139733.39, stdev=1645.28, samples=240
   iops        : min=34419, max=35793, avg=34933.05, stdev=411.41, samples=240
  lat (nsec)   : 500=0.01%
  lat (usec)   : 10=0.01%, 20=0.20%, 50=0.01%, 100=34.85%, 250=64.52%
  lat (usec)   : 500=0.43%, 750=0.01%
  cpu          : usr=41.10%, sys=58.90%, ctx=59, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.1%, 4=151.9%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=4167941,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
   READ: bw=136MiB/s (142MB/s), 136MiB/s-136MiB/s (142MB/s-142MB/s), io=15.9GiB (17.1GB), run=120001-120001msec

Disk stats (read/write):
  sda: ios=4/44, merge=0/28, ticks=8/72, in_queue=80, util=0.04%

**Comment by dhongMicron** [comment]
The fio outputs show average round trip latency for iodepth 1 is 104.24 usec, and iodepth 4 is 114.89 usec.
What's the problem again?

**Comment by arashta** [comment]
Thanks, Deyoung,
Actually, I have found that fio works correctly. 
But, I need more flexibility than what is provided by fio. So, I considered modifying the unvme_lat_test.c file. However, this file reports unrealistic results. As I mentioned in an earlier comment, for qdepth = 1 and request size = 8 (4kB), the reported average read latency value is 22.7us.  As I realized, the unvme_lat_test.c measures the time from calling unvme_aread to unvme_apoll. And this time is very small! Is there something happing that I am not aware of? Does the time duration between unvme_aread and unvme_apoll reflect the I/O job execution latency?

**Comment by dhongMicron** [comment]
I've changed unvme_lat_test to use random LBA but it shows little difference.  I've also experimented changing to use clock_gettime() but didn't get different results either so I don't bother changing it.  I can't find anything wrong with the test itself but consider the test to be more of an example than a performance tool.  You're welcome to play with the code.

For actual performance evaluation, you should use fio which is more of a standard tool that many are using.  It provides a rich set of parameters that you can customize.

Thanks!
