### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by arashta** [MicronSSD/unvme#19]
Hi,
It seems that the library has thread safety issues. I used asynchronous I/O job submission (i.e., unvme_awrite and unvme_aread functions) in thread #1 of my program, and in another thread (i.e., thread #2) checked for the completion of I/O jobs. The result was always an error saying: "pending cid %d not found".

After checking different possible solutions, I found that if I protect job submission and job polling code regions with a lock, everything would be fine.

**Comment by dhongMicron** [comment]
For some reason I did not get an email notification for this posting.  

As indicated in the README file (under unvme_write), thread safe I/O operation must be done within an NVMe queue.  Each I/O queue is restricted by one thread, so the max number of threads your application can have is limited by the number of NVMe queues supported by the device.  It is designed for performance throughput and to avoid unnecessary locking.

**Comment by dhongMicron** [comment]
For some reason I did not get an email notification for this posting.

As indicated in the README file (under unvme_write), thread safe I/O operation must be done within an NVMe queue. Each I/O queue is restricted by one thread, so the max number of threads your application can have is limited to the number of NVMe queues supported by the device. It is designed for performance throughput to avoid unnecessary locking. See examples unvme_lat_test.c, unvme_mts_test.c, unvme_mcd_test.c under test/unvme directory.
