### ISSUE TITLE
Error using unvme for micron 2200 and Intel 900P

### ISSUE THREAD

**Issue by mohammadrezasaed** [MicronSSD/unvme#23]
Hi,

I'm trying to use unvme to run some tests on Intel Optane 900P, but i get the following error on every test:
ERROR: vfio_create ioctl VFIO_SET_IOMMU
I also tried to connect to Micron 2200 on the same system and got the same error.
VT-d is enabled in the BIOS and VFIO is configured correctly.
I would appreciate if you could help me out.

Thanks,
Saed

**Comment by dhongMicron** [comment]
Hi Saed,
I assume you follow the README.md instructions.  I have some questions:

+ What OS and kernel version are you using?
    $ cat /etc/system-release
    $ uname -a

+ What does 'ls /sys/kernel/iommu_groups/' output?  
If VFIO is setup correctly, there should be a list of directories with number name there.

+ You can verify if vfio modules can be loaded using the following commands:
    $ sudo modprobe vfio_pci vfio
    $ lsmod | grep vfio
    vfio_pci               49152  0
    vfio_virqfd            16384  1 vfio_pci
    vfio_iommu_type1       24576  0
    vfio                   36864  2 vfio_iommu_type1,vfio_pci
    irqbypass              16384  2 kvm,vfio_pci

**Comment by mohammadrezasaed** [comment]
I have followed the README.md instructions.

- I am using Ubuntu with kernel version 4.15.0.
$ uname -a
Linux safari-System-Product-Name 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- '/sys/kernel/iommu_groups/' folder is not empty.
$ ls /sys/kernel/iommu_groups/
0  10  12  14  16  18  2   21  23  4  6  8
1  11  13  15  17  19  20  22  3   5  7  9

- I think vfio module is loaded.
$ sudo modprobe vfio_pci vfio
$ lsmod | grep vfio
vfio_pci               45056  0
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       24576  0
vfio                   28672  2 vfio_iommu_type1,vfio_pci
irqbypass              16384  2 vfio_pci,kvm

Thank you for your response.

**Comment by dhongMicron** [comment]
Sorry for late reply.  

I assume you know, but just to make sure you specify the correct PCI device associated, run 
$ lspci | grep Non-Volatile
to get the list of NVMe devices.

VFIO appears to be ready on your system.  I haven't tested kernel 4.15 but assume you know how to build your kernel.  One other thing that can go wrong is that /usr/include/linux/vfio.h is incompatible with your kernel.  Debug steps:

1)  From your kernel 4.15.0 source, see Documentation/kbuild/headers_install.txt and try that.  See also Documentation/vfio.txt. After running 'make headers_install' then rebuild your unvme code 'make clean all' and retry.

2) If that still fails, you'll have to use gdb, and walk through vfio_create().  Remake with 'CFLAGS=-g make clean all' and stop in vfio_create()

**Comment by mohammadrezasaed** [comment]
IOCTL on line 352 of file unvme_vfio.c fails with errno 1: Operation not permitted.
Thanks again for your response.

**Comment by mohammadrezasaed** [comment]
I found the same IOCTL error with same file and arguments on the following link:
https://www.mail-archive.com/kvm@vger.kernel.org/msg73074.html

It was suggested to run the following commands and it seems that the issue is resolved.
# modprobe -r vfio_iommu_type1
# modprobe vfio_iommu_type1 allow_unsafe_interrupts=1

**Comment by dhongMicron** [comment]
Thanks Saed for the info.  Closing this issue.
