### ISSUE TITLE
Why the current code no longer supports the three different UNVMe models

### ISSUE THREAD

**Issue by abner-ma** [MicronSSD/unvme#24]
I found that there are three different UNVMe models on the Wiki, but I find that the current code is not the case. I am curious why the client-serve model is removed.For performance？

**Comment by dhongMicron** [comment]
The three models were initially developed for evaluation.  We concluded (a few years back) that this simple polling mechanism is the best performance model to use.

**Comment by abner-ma** [comment]
> The three models were initially developed for evaluation. We concluded (a few years back) that this simple polling mechanism is the best performance model to use.

thank you for your answer
