### ISSUE TITLE
NVMe device not found error in secure erase after unvme-setup reset command

### ISSUE THREAD

**Issue by arghavanmh** [MicronSSD/unvme#25]
I have an SSD of type MTFDHAL800MCE from Micron technology. My system is based on Mint18 installed on an HDD not the SSD. I connect to this system remotely using putty. Micron has provided a Storage Executive CLI as a tool to run specific commands on the SSDs. The links for the msecli user guide and the datasheet for my SSD is available here: [msecli-userguide](https://www.micron.com/-/media/client/global/documents/products/software/storage-executive-software/msecli/storage_executive_cli_user_guide.pdf?la=en) and [SSD-datasheet](https://datasheet4u.com/datasheet-pdf/Micron/MTFDHAL800MCE/pdf.php?id=1248509).

I used the command ` unvme-setup reset` to change access to the SSD to the kernel space. It successfully changed from `UNVMe-enabled` to `/dev/nvme0`. I, also, checked it with` msecli -L` which displayed all devices in my system. Then, I used the msecli secure erase command, page 45 of msecli-userguide, to perform a secure erase on my NVMe SSD. 

However, after an hour it failed with the error message `the device not found` and the NVMe SSD was no more detected by fdisk, sfdisk, or gparted. I rebooted the system by `sudo shutdown -r now`, but nothing changed. Why the SSD is no more recognized and how can I fix this?

**Comment by dhongMicron** [comment]
UNVMe is a userspace driver.  Msecli is an application talking to the kernel space driver.  The two are unrelated.  You're posting to the wrong place.
