### ISSUE TITLE
pciaccess.h isn't always available (nor is it needed it seems).

### ISSUE THREAD

**Issue by ttDSSD-EMC** [MicronSSD/unvme#3]
On CentOS 7, src/unvme_fio.c fails to compile because the pciaccess.h header isn't found.
Just deleting this line seems to work.

I can prep a pull request if this is acceptable.

**Comment by dhongMicron** [comment]
Thanks for the info, pciaccess.h was legacy and not needed.  I checked in the fix.

**Comment by ttDSSD-EMC** [comment]
thanks
