### ISSUE TITLE
unvme fails on Sandy Bridge because the IOMMU only has 39 bits.

### ISSUE THREAD

**Issue by ttDSSD-EMC** [MicronSSD/unvme#4]
The VFIO_IOVA is set to 0x8800000000 requires 40 bits.  On my Xeon E3-1245 V2 this
causes the ioctl() to fail, with the kernel spewing

`[429200.701588] intel_iommu_map: iommu width (39) is not sufficient for the mapped address (8800001000)`

Changing it to 0x800000000 fixes this issue.

I'm not sure which fix is preferred here.

**Comment by dhongMicron** [comment]
VFIO_IOVA can be anything (including 0).  I just chose a pattern for me to detect when looking at the command buffer.  I checked in the fix as you pointed out by reducing that IOMMU address range to 36-bit.  Thanks.

**Comment by ttDSSD-EMC** [comment]
Why was it reopened?  It Works for Me(TM).

**Comment by dhongMicron** [comment]
Oh, I just wanted to let the one who opened the issue close it.
