### ISSUE TITLE
Really minor: divide is slow and serializing

### ISSUE THREAD

**Issue by ttDSSD-EMC** [MicronSSD/unvme#6]
It might not matter too much, but it irks me: the divides in unvme_fio.c

         u64 slba = io_u->offset / unvme.ns->blocksize;
         int nlb = io_u->xfer_buflen / unvme.ns->blocksize;

are slow (divide is a serializing and generally slow instruction).  Since I doubt
NVMe will ever support non-powers-of-two sizes, it might be worth computing

        unvme.ns->blocksize_lg2 = log2(unvme.ns->blocksize);

at init and use shifts

         u64 slba = io_u->offset >> unvme.ns->blocksize_lg2;
         int nlb = io_u->xfer_buflen >> unvme.ns->blocksize_lg2;

where log2() is left as an exercise for the reader.

**Comment by dhongMicron** [comment]
Ok, I added the pageshift and blockshift values to the unvme_ns_t structure.

**Comment by ttDSSD-EMC** [comment]
thanks
