### ISSUE TITLE
Can't run unvme_lat_test on Toshiba SSD

### ISSUE THREAD

**Issue by banandan** [MicronSSD/unvme#7]
Hi, 
I am able to test unvme on an Intel SSD but could not run unvme on Toshiba SSD. I have attached the log file. Any help would be appreciated.
[unvme.txt](https://github.com/MicronSSD/unvme/files/360021/unvme.txt)

Thanks,
Bala

**Comment by banandan** [comment]
Without the -DUNVME_DEBUG option, I get the error

LATENCY TEST BEGIN
ERROR: nvme_ctlr_wait_ready timeout waiting for ready 0
ERROR: unvme_adminq_create nvme_setup_adminq

**Comment by dhongMicron** [comment]
The debug log shows it failed creating the first IO completion queue for some reason.  I don't have a Toshiba SSD to test with.  I would expect none of the tests under test/unvme to pass, and you should see the same ERROR message whether you enable -DUNVME_DEBUG or not.

Anyway, I've made a file name change, so application would now include "unvme.h" instead of "libunvme.h."  That should not make any difference regarding your problem.  However, I've also made a change in unvme_nvme.c in function nvme_acmd_create_cq() to not set the cmd->iv,  Not sure if that will fix your problem.

I assume you can use the inbox kernel driver with your Toshiba SSD?
Let me know your progress.  Thanks.

**Comment by banandan** [comment]
Yes, I am able to use Toshiba SSD with kernel driver.

I was getting different ERROR messages depending upon  -DUNVME_DEBUG option. The recent modification seems to have fixed the problem when I enable -DUNVME_DEBUG option.

But, if DUNVME_DEBUG  is disabled, I still get the error

LATENCY TEST BEGIN
ERROR: nvme_ctlr_wait_ready timeout waiting for ready 0
ERROR: unvme_adminq_create nvme_setup_adminq

Thanks a lot for the help.

**Comment by dhongMicron** [comment]
Are you able to run any other test besides unvme_lat_test?  How about these tests:

$ test/nvme/nvme_identify xx:xx.x
$ test/nvme/nvme_identify xx:xx.x 1
$ test/nvme/nvme_get_log_page xx:xx.x 1 1
$ test/nvme/nvme_get_log_page xx:xx.x 1 2
$ test/nvme/nvme_get_log_page xx:xx.x 1 3
$ test/unvme/unvme_sim_test xx:xx.x
$ test/unvme/unvme_api_test xx:xx.x
$ test/unvme/unvme_mts_test xx:xx.x

I would expect they all failed the same way (unless get_log_page is not supported by Toshiba SSD).

Anyway, it looks like there is a timing issue and it failed in nvme_ctlr_enable(), when the controller is enabled.

When it failed, anything appears in dmesg (or /var/log/messages)?
And what Linux and kernel version are you using?

**Comment by banandan** [comment]
If DUNVME_DEBUG  is disabled, then every test fails with timeout

ERROR: nvme_ctlr_wait_ready timeout waiting for ready 0
nvme_setup_adminq

If  DUNVME_DEBUG  is enabled, then only '$ test/nvme/nvme_get_log_page xx:xx.x 1 2' fails with
ERROR: nvme_check_completion q=0 cid=0 stat=0x4 (dnr=1 m=1 sct=0 sc=0x2) (C)
ERROR: nvme_wait_completion status 0x4
nvme_acmd_get_log_page

I am using Ubuntu 3.19.0-64-generic. All I see from dmesg is the following
[53301.978816] vfio-pci 0000:83:00.0: enabling device (0400 -> 0403)
[53302.082901] vfio_ecap_init: 0000:83:00.0 hiding ecap 0x19@0x300

**Comment by banandan** [comment]
I used some 'printf' statements in 'nvme_ctlr_wait_ready' and it looks like 'cap.to' is set to '0'.

**Comment by dhongMicron** [comment]
Hmm, what's the hex value of cap.val?  What if you put a sleep(1) before the line (in unvme_nvme.c)
cap.val = r64(dev, &dev->reg->cap.val);
Could it be that after nvme_ctlr_enable() a delay is needed?  

This can be your workaround but I would try kernel 4.6.x to see if it also resolves your problem.

Can you try building the kernel 4.6.4?  I ran into a similar device timing problem on certain machine, and Alex Williamson (VFIO owner) suggested the fix he put in kernel 4.6.  See his note at https://lkml.org/lkml/2016/2/22/771.  It resolved my issue, and I think it may resolve this one, too.

**Comment by banandan** [comment]
I think the error happens in "nvme_ctlr_disable". 
sleep(1) before  r64(dev, &dev->reg->cap.val); does not help but sleep(1) after  r64(dev, &dev->reg->cap.val); solves the issue.
Also,
memcpy(&val,addr,sizeof(u64)); instead of 'u64 val = *addr' within r64() fixes the issue.

**Comment by dhongMicron** [comment]
Regarding sleep and memcpy, what if you compile using -g instead of -O3 (in Makefile.def).

I do think this problem is related to FLR delay, and it can be resolved using kernel 4.6x, or alternatively change the kernel source drivers/pci/pci.c with the patch from Alex as specified above.

Glad you find the work around.  Thanks.

**Comment by banandan** [comment]
I disabled -O3 and everything works fine (without sleep() or memcpy()). I don't think -g would make any difference. 

I still can't run './test/nvme/nvme_get_log_page 83:00.0 1 2' in any of the SSDs though.
ERROR: nvme_check_completion q=0 cid=0 stat=0x4 (dnr=1 m=1 sct=0 sc=0x2) (C)
ERROR: nvme_wait_completion status 0x4
nvme_acmd_get_log_page

Thanks.

**Comment by banandan** [comment]
I even tried with -O2 and it is working fine. Changing it to -O3 creates timeouts. Looks like -O3 optimization is introducing some discrepancy.

**Comment by dhongMicron** [comment]
It might also be the version of the compiler, too.  I'm using
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

Anyway, it's probably better to set COPT?=-O2 in Makefile.def.

Regarding get_log_page command, it looks like you can run "nvme_get_log_page 83:00.0 1 1" using log_page_id 1?  That may give some clue to why log_page_id 2 failed.  My Intel SSD works fine.  Is your Intel SSD not working?

**Comment by banandan** [comment]
I am using gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 on both the machines. Timeout happens on only one of the machines. 

lba is set to 2 on my Intel SSD and 0 on Toshiba. Looks like it does not support SMART log, although the log_page_id 1 and 3 runs on both the machines without any error.

**Comment by dhongMicron** [comment]
Sounds like you're all set.  
Thanks for finding issues.

**Comment by banandan** [comment]
Thanks  a lot for the help.
